#!/usr/bin/env fish

set root "../"
set src "$root/src/kern/"
set cmd "fish -c 'sleep 0"
set salt_root "/salt"

function show_help
	echo -e "Usage:\n  ./manage build copy clean up umount rmmod insmod mount ls"
	exit 0
end
contains help $argv; or contains -- '--help' $argv; or contains -- '-h' $argv; and show_help

contains build  $argv; and /opt/clion/bin/cmake/bin/cmake --build /home/romas/.clion10/system/cmake/generated/e206224e/e206224e/Debug --target saltfs
contains copy   $argv; and cp -f $src/saltfs.ko $root/bin/
contains clean  $argv; and cd $src; and ./clean.fish; and cd -
contains up     $argv; and vagrant up
# contains umount $argv; and set cmd "$cmd; and umount $salt_root; and umount /salt 2>&1 | grep -q 'not mounted'; and sleep 3; and umount $salt_root; true"
contains umount $argv; and set cmd "$cmd; and umount $salt_root; true"
contains rmmod  $argv; and set cmd "$cmd; and rmmod --force saltfs; true"
contains insmod $argv; and set cmd "$cmd; and insmod /module/saltfs.ko"
contains mount  $argv; and set cmd "$cmd; and mkdir -p $salt_root; mount -t saltfs saltfs $salt_root"
contains ls     $argv; and set cmd "$cmd; and ls $salt_root"

set cmd "$cmd'"

vagrant ssh -c $cmd
