#!/usr/bin/env fish

function vm_ssh
	while not vagrant ssh
		sleep 1
	end
end

function vm_check_running
	vagrant status | grep -q 'running'
end

function vm_check_not_created
	vagrant status | grep -q 'not created'
end

function vm_fix
	set max_try 3
	for i in (seq $max_try)
		if not vm_check_not_created
			break
		end

		echo "Trying to fix vm, try #$i"

		vagrant halt --force
		rm -rf .vagrant/
		uncpbak .vagrant.20150106_204039.bak/
		vagrant up
	end

	while not vagrant ssh -c 'ls /module/saltfs.ko >/dev/null'
		vagrant reload
	end

	echo "It seems vm is fixed"
end

function vm_reload
	vagrant halt $argv
	vm_fix
end

[ (count $argv) -gt 1 ]; and set vm_argv $argv[2..-1]

contains fix $argv; or vm_check_not_created; and vm_fix
contains ssh $argv;                          and vm_ssh $vm_argv
contains reload $argv;                       and vm_reload $vm_argv
